project_id: "462472"
base_path: .
base_url: https://api.crowdin.com

files:
  - source: /resources/locales/en-US/*.ftl
    translation: /resources/locales/%two_letters_code%/%original_file_name%
    skip_untranslated_strings: true
    skip_untranslated_files: true
    export_only_approved: true
