services:
  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "status" ]
      interval: 5s
      timeout: 5s
      retries: 3

  database:
    build:
      context: .
      target: database
    environment:
      - DB_URL
    ports:
      - 50052:50051

  gateway:
    build:
      context: .
      target: gateway
    environment:
      - TOKEN
      - GATEWAY_URL
      - SHARD_ID=0
      - SHARD_TOTAL=1
      - INTENTS=32509
      - STATUS
      - ACTIVITY_TYPE
      - ACTIVITY_NAME
      - ACTIVITY_URL
      - AMQP_URL=amqp://rabbitmq:5672
      - AMQP_EXCHANGE=gateway
    depends_on:
      rabbitmq:
        condition: service_healthy

  imgen:
    build:
      context: .
      target: imgen
    environment:
      - IMAGE_DIR=/images
    volumes:
      - ./images:/images
    ports:
      - 50051:50051
