# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poketwo/gateway/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from poketwo.discord.v1 import models_pb2 as poketwo_dot_discord_dot_v1_dot_models__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fpoketwo/gateway/v1/events.proto\x12\x12poketwo.gateway.v1\x1a\x1fpoketwo/discord/v1/models.proto\"=\n\rMessageCreate\x12,\n\x07message\x18\x01 \x01(\x0b\x32\x1b.poketwo.discord.v1.Messageb\x06proto3')



_MESSAGECREATE = DESCRIPTOR.message_types_by_name['MessageCreate']
MessageCreate = _reflection.GeneratedProtocolMessageType('MessageCreate', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGECREATE,
  '__module__' : 'poketwo.gateway.v1.events_pb2'
  # @@protoc_insertion_point(class_scope:poketwo.gateway.v1.MessageCreate)
  })
_sym_db.RegisterMessage(MessageCreate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGECREATE._serialized_start=88
  _MESSAGECREATE._serialized_end=149
# @@protoc_insertion_point(module_scope)
